# Introduction

Having looked at some basic string and file manipulation let's move our attention to data handling. So far we've tended to think of lists of data, but what happens when we want tables of data and more high dimensional data? We've learnt some things that help but of course Python has some specific modules for dealing with this kind of problem.





# Data Handling
Welcome to this Python notebook on data handling. We will start by looking at some slightly more advanced data structures in a package called numpy before moving into a package called pandas.

We will look at some standard ways to manipulate data and how to work on data files we might create, of obtain from third party sources.

First, we will start with a quick recap of some basic data structures.

Copy this code into the cell below a bit at a time and check you understand what it is doing.

```
# Let's start by creating a list of numbers

v = [1.2,3.5,4.4,5.2,6.7]
print(f"v : {v}\n")

a = [v,v,[3,4,6,7,9]]
print(f"a : {a}\n")

# let's try and multiply all the numbers in a by 2
print(f"a*2 {a*2}\n")

# let's try again
for i in a:
  for j in i:
    print(j*2)

# well that kind of worked, but if you've used vectors and arrays in maths you know it's not really what I wanted.```



In [9]:
# Copy the code into this cell



## NumPy
Let me intructroduce numpy short for numerical py. We've seen how libraries can introduce functions that we reuse, well some packages (including numpy) also introduce new types to the language. These new types are aware of what their purpose is and and allow us to do clever things to them very quickly.

In [6]:
# Let's first import our package and give it a short name np.
import numpy as np

# We can take the list we already created and convert it to an array like this.
v2 = np.array(v)

print(f"Original {v} , multiplied array {v2*2}")


Original [1.2, 3.5, 4.4, 5.2, 6.7] , multiplied array [ 2.4  7.   8.8 10.4 13.4]


In [8]:
# and of course we can create 2 dimensional lists

ar = np.array([[1.2, 2.3, 3.4],
              [2.2, 3.2, 4.6],
              [5.2, 1.2, 2.3]])
print(f"{ar=}")
print(f"{ar*2=}")

ar=array([[1.2, 2.3, 3.4],
       [2.2, 3.2, 4.6],
       [5.2, 1.2, 2.3]])
ar*2=array([[ 2.4,  4.6,  6.8],
       [ 4.4,  6.4,  9.2],
       [10.4,  2.4,  4.6]])


In [ ]:
# we can also create arrays of a particular size using some special numpy functions.

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(2,2))


print(x1)
print(x2)

# if you ever want to see the size of an array you can ask it's shape
print(f"shape of x1 : {x1.shape}")  # 6 rows
print(f"shape of x2 : {x2.shape}")  # 2 rows, 2 columns


[5 9 3 0 5 0]
[[1 2]
 [4 2]]
shape of x1 : (6,)
shape of x2 : (2, 2)


In [ ]:
# Numpy gives us lots of tools for looking at data.
# Let's start by creating an artificial set of data.
# imagine we have surveyed 100 people and get their ages

# Notice that lot's of functions have named parameters this allows is to
# be a bit more descriptive in our

ages = np.random.randint(low = 18, high= 70, size = 100)

In [ ]:
# having created our data, what can we do with it?

print(f"Maximum age is {np.max(ages)}")

# Try the following np summary statistic functions
# np.min()
# np. std()
# np.mean()
# np.median()
# np.size()

# Remember the ? in Jupyter notebooks for help.


Maximum age is 69


In [ ]:
# We also have some nice data manipulation functions.
# look at the following.

arr = np.array([45, 32,19,99,67])
arr.sort()
print(arr)
# notice doesn't applies in place, i.e. the array is sorted when we run the function
# we don't need to allocate the output.

# Try the following functions and see what they do.
# remember that the environment will give you hints about parameters etc.

# 1. reverse()
# 2. append()
# 3. pop()
# 4. remove()



[19 32 45 67 99]


## Data as tables

So having seen how we can create an array of numbers it's not hard to see how this could be viewed as a table. Imagine a set of information about people where each row is a person and each column a feature, e.g. age, height, ...

In this next section we will look at accessing information in the table and taking slices of the table to work with.

In [ ]:
# Let's start by creating a table of random numbers which has 4 rows and 6 columns
np.random.seed(0) # this is a little trick to make sure always get the same sequence from our random number generator
tbl = np.random.randint(10, size=(4,6))
print(tbl)

# to access a single value from the table we will simply give it the row and column we want
# notice that rows and columns are 0 indexed
print(tbl[0,1])


# change the values in the square brackets to check you understand what it happening.

[[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]]
0


In [ ]:
# of course we might want more than just one element.

# Can you explain what these do?

print(tbl[:, 2])
print("")

print(tbl[1, :])
print("")

print(tbl[0:2, 1:4])
print("")

print(tbl[0,3:])

# What does the colon operator do?
# are the paramters inclusive or exclusive?

[3 2 1 5]

[3 5 2 4 7 6]

[[0 3 3]
 [5 2 4]]

[3 7 9]


## Challenge

In [10]:
# Challenge
# Use the summary statistics you learnt earlier to find summaries (min max and mean) for
# The whole table
# Each Column
# Each Row

# Use loops and formatted printing to show your results



# Pandas

So we've seen some basic numeric arrays, let's turn our attention to pandas.

Pandas is a module which specialises data table operations. You can think of it a little like Pythons version of Excel. So pretty much anything you would like to do in Excel can be done programatically in Python. But, you won't be surprised to hear, it's much more powerful.

In [11]:
# First, just like we converted a list to an array, let's turn an array into a pandas dataframe
import pandas as pd

# Uncomment the code create a data frame

#df = pd.DataFrame(tbl)
#print(df)
#print("")

# you can see the same data we has as before but now every row and column has an id.
# now let's try adding something meaningful to the column headings
#df.columns = ['A', 'B', 'C', 'D', 'E', 'F']
#print(df)
#print("")

# note we could also have just said
#df = pd.DataFrame(tbl, columns = ['A', 'B', 'C', 'D', 'E', 'F'])
#print(df)
#print("")


In [12]:
# Alternatively we can create a dataframe using a dictionary
# Uncomment the code to see how this works


#df = pd.DataFrame(tbl, columns = ['A', 'B', 'C', 'D', 'E', 'F'])
#data = {'Name':['Alex', 'Bob', 'Charlie', 'Samj'],
#        'Age':[27, 45, 22, 32],
#        'Address':['London', 'Paris', 'York', 'Newcastle'],
#        'Qualification':['Msc', 'MA', 'BEng', 'Phd']}

#df = pd.DataFrame(data)
#print(df)

In [ ]:
# Because this is a pandas dataframe we also get access to some new special functions
# Uncomment each of these and explain what they do

# df.head(2)
# df.loc[1:3, ['Name', 'Qualification']]

# remember you can use the ? in Jupyter


# Score Book data

Before you start running code cells in this part of the notebook you will need to upload three files: Scorebook.csv, Scorebook2.csv and Scorebook3.csv.

These are simple comma separated value files that I created offline, imagine they came from a google form or Excel.

In [ ]:
# Pandas gives us a nive read_csv funtion which knows how to deal with files in this form


df = pd.read_csv('ScoreBook.csv')

# having read in the data we can look at the table
print(df)

   participant  age  pref  score_1  score_2  score_3
0         1234   25     1       45       18       89
1        56782   18     1       67       32       42
2        36789   19     0       32       76       54
3        46923   32     0       78       46       67
4        56723   47     0       78       48       32
5        61378   65     1       82       87       67
6        74892   22     1       45       46       89
7        85243   29     0       56       75       82
8        97823   36     0       52       24       63
9        10674   44     1       12       56       67


In [ ]:
# If we want to know some quick summary statistics for the table then we can use
# the Pandas describe function.
df.describe()

participant        age       pref    score_1    score_2    score_3
count     10.00000  10.000000  10.000000  10.000000  10.000000  10.000000
mean   52846.10000  33.700000   0.500000  54.700000  50.800000  65.200000
std    30545.09564  14.787758   0.527046  22.405604  22.996618  18.843213
min     1234.00000  18.000000   0.000000  12.000000  18.000000  32.000000
25%    39322.50000  22.750000   0.000000  45.000000  35.500000  56.250000
50%    56752.50000  30.500000   0.500000  54.000000  47.000000  67.000000
75%    71513.50000  42.000000   1.000000  75.250000  70.250000  78.250000
max    97823.00000  65.000000   1.000000  82.000000  87.000000  89.000000

In [ ]:
# Acouple of notes.
#
# The first participant is only 4 characters while the others are 5.
# The describe function is telling us the mean of the participant id. That makes no sense.
# Similarly we are seeing preference as 0 and 1 and not True and False.
#
# Why?
#
# it's because the reader is trying to be helpful and assumes that the.columns
# are integers. We can helpp pandas by giving it the correct data types

df = pd.read_csv('ScoreBook.csv', dtype={'participant' : 'string', 'pref': 'bool'})
df

participant  age   pref  score_1  score_2  score_3
0       01234   25   True       45       18       89
1       56782   18   True       67       32       42
2       36789   19  False       32       76       54
3       46923   32  False       78       46       67
4       56723   47  False       78       48       32
5       61378   65   True       82       87       67
6       74892   22   True       45       46       89
7       85243   29  False       56       75       82
8       97823   36  False       52       24       63
9       10674   44   True       12       56       67

In [ ]:
# Now let's run the describe function
df.describe()

age    score_1    score_2    score_3
count  10.000000  10.000000  10.000000  10.000000
mean   33.700000  54.700000  50.800000  65.200000
std    14.787758  22.405604  22.996618  18.843213
min    18.000000  12.000000  18.000000  32.000000
25%    22.750000  45.000000  35.500000  56.250000
50%    30.500000  54.000000  47.000000  67.000000
75%    42.000000  75.250000  70.250000  78.250000
max    65.000000  82.000000  87.000000  89.000000

In [ ]:
# Of course I brought in this data because I want to manipulate it.
#
# I want to create a new column on this data which is the calculated
# from the values in other columns. Mayve we have a weight 'total' score
# where  score 3 is worth twice as much as the other two


df['total'] = df['score_1'] + df['score_2'] + df['score_3']*2


# Putting the name of a new column in the square brackets says we are
# going to add a column using whatever is on the right side of the
# = sign.

# I also want the total as a percentage

df['percentage'] = df['total']/4

print(df)

  participant  age   pref  score_1  score_2  score_3  total  percentage
0       01234   25   True       45       18       89    241       60.25
1       56782   18   True       67       32       42    183       45.75
2       36789   19  False       32       76       54    216       54.00
3       46923   32  False       78       46       67    258       64.50
4       56723   47  False       78       48       32    190       47.50
5       61378   65   True       82       87       67    303       75.75
6       74892   22   True       45       46       89    269       67.25
7       85243   29  False       56       75       82    295       73.75
8       97823   36  False       52       24       63    202       50.50
9       10674   44   True       12       56       67    202       50.50


In [ ]:
# Sometimes you might wantto delete a column. Maybe it's confidential and you
# want to remove it before to circulate the data.

# To drop a column,  we need to give it the name of the column and an axis of 1, whch means column

df.drop(['age'], axis=1)
print(df)

  participant  age   pref  score_1  score_2  score_3  total  percentage
0       01234   25   True       45       18       89    241       60.25
1       56782   18   True       67       32       42    183       45.75
2       36789   19  False       32       76       54    216       54.00
3       46923   32  False       78       46       67    258       64.50
4       56723   47  False       78       48       32    190       47.50
5       61378   65   True       82       87       67    303       75.75
6       74892   22   True       45       46       89    269       67.25
7       85243   29  False       56       75       82    295       73.75
8       97823   36  False       52       24       63    202       50.50
9       10674   44   True       12       56       67    202       50.50


In [ ]:
# Well that didn't seem to work! Why not?

# The answer is that the drop function doesn't change the data frame. It
# returns a dataframe where the column has been dropped.

df_noage = df.drop(['age'], axis=1)
print(df_noage)

  participant   pref  score_1  score_2  score_3  total  percentage
0       01234   True       45       18       89    241       60.25
1       56782   True       67       32       42    183       45.75
2       36789  False       32       76       54    216       54.00
3       46923  False       78       46       67    258       64.50
4       56723  False       78       48       32    190       47.50
5       61378   True       82       87       67    303       75.75
6       74892   True       45       46       89    269       67.25
7       85243  False       56       75       82    295       73.75
8       97823  False       52       24       63    202       50.50
9       10674   True       12       56       67    202       50.50


In [ ]:
# Of course we might also want to remove rows from the data set.
# Maybe there is an individual who has removed consent.

# Here we change to axis=0 which means row.
# the number in the square brackets is the row index.
result = df_noage.drop([3], axis=0)

print(result)

  participant   pref  score_1  score_2  score_3  total  percentage
0       01234   True       45       18       89    241       60.25
1       56782   True       67       32       42    183       45.75
2       36789  False       32       76       54    216       54.00
4       56723  False       78       48       32    190       47.50
5       61378   True       82       87       67    303       75.75
6       74892   True       45       46       89    269       67.25
7       85243  False       56       75       82    295       73.75
8       97823  False       52       24       63    202       50.50
9       10674   True       12       56       67    202       50.50


In [ ]:
# Removing a row by row number is fine, but we might end up shuffling row numbers
# it would be better to use information in the row.
# for example the participant id,
# This takes a little explaining, so bear with me.

# Firstly we can get a simple boolean check to see if a value in a column matches a value we are interested in
df['participant'] == '46923'

# notice this is run for every row, we don't need a loop, that's one of the
# powerful things about pandas. Removing the loops makes it quick for even quite
# large data sets.

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
Name: participant, dtype: boolean

In [ ]:
# if we pass this list of booleans into the dataframe we get

df[df['participant']== '46923']

# ie. It will return the rows where the boolean is a True.

participant  age   pref  score_1  score_2  score_3  total  percentage
3       46923   32  False       78       46       67    258        64.5

In [ ]:
# Then we can ask for the index of this row
idx = df[df['participant']== '46923'].index
print(f"Index : {idx.values}")


Index : [3]


In [ ]:
# Having got the index we can now drop the
# participant that is a problem and save the new data set

df_dropped_person = df.drop(idx)
print(df_dropped_person)

  participant  age   pref  score_1  score_2  score_3  total  percentage
0       01234   25   True       45       18       89    241       60.25
1       56782   18   True       67       32       42    183       45.75
2       36789   19  False       32       76       54    216       54.00
4       56723   47  False       78       48       32    190       47.50
5       61378   65   True       82       87       67    303       75.75
6       74892   22   True       45       46       89    269       67.25
7       85243   29  False       56       75       82    295       73.75
8       97823   36  False       52       24       63    202       50.50
9       10674   44   True       12       56       67    202       50.50


In [ ]:
# Of course this isn't just about deleting rows. This kind of search functionality can
# be really useful in finding subsets of the data.
#
# Why are we doing it this complicated way, well the reason is that we can select
# multiple lines

older = df[df['age'] >= 30]
younger = df[df['age']<30]

print('Older participants')
print(older)
print()
print('Younger participants')
print(younger)

Older participants
  participant  age   pref  score_1  score_2  score_3  total  percentage
3       46923   32  False       78       46       67    258       64.50
4       56723   47  False       78       48       32    190       47.50
5       61378   65   True       82       87       67    303       75.75
8       97823   36  False       52       24       63    202       50.50
9       10674   44   True       12       56       67    202       50.50

Younger participants
  participant  age   pref  score_1  score_2  score_3  total  percentage
0       01234   25   True       45       18       89    241       60.25
1       56782   18   True       67       32       42    183       45.75
2       36789   19  False       32       76       54    216       54.00
6       74892   22   True       45       46       89    269       67.25
7       85243   29  False       56       75       82    295       73.75


In [ ]:
# And if you need to you could of course create a function to drop
# if you find yourself wanting to do this lots then remember you
# can always write a function to drop rows based on a columns value

def drop_row(df, value, col_name='participant'):
  idx = df[df[col_name]== value].index
  df2 = df.drop(idx)
  return df2

result = drop_row(df, '46923')
result = drop_row(result, '85243')
result = drop_row(result, '10674')

print(result)

  participant  age   pref  score_1  score_2  score_3  total  percentage
0       01234   25   True       45       18       89    241       60.25
1       56782   18   True       67       32       42    183       45.75
2       36789   19  False       32       76       54    216       54.00
4       56723   47  False       78       48       32    190       47.50
5       61378   65   True       82       87       67    303       75.75
6       74892   22   True       45       46       89    269       67.25
8       97823   36  False       52       24       63    202       50.50


## Saving your data

Having made these changes let's write the data to a new file so we can distribute it.

In [ ]:
# having edited our file, let's save it.
# remember you'll need to download it from jupyter if you want to keep it.
result.to_csv('new_score_book.csv', encoding='utf-8')

# Once you've saved it download it and open it in Excel.

In [ ]:
# Before we move on I just want to highlight a useful function for when you're
# reading in some data. You might find that the column names are a bit cumbersome,
# especially when you want to include them in lines of code.


# In that case we can rename them to something more friendly.


df = df.rename(columns={"participant":"id", "pref":"preference"})
print(df.head(2))

      id  age  preference  score_1  score_2  score_3  total  percentage
0  01234   25        True       45       18       89    241       60.25
1  56782   18        True       67       32       42    183       45.75


In [ ]:
# So a few time now I've used the df = df.... form of a function.
# We can force what is called inplace operations for quite a few
# pandas fucntions like this.

df.rename(columns={ df.columns[2]: "pref" }, inplace=True)
print(df.head(2))

      id  age  pref  score_1  score_2  score_3  total  percentage
0  01234   25  True       45       18       89    241       60.25
1  56782   18  True       67       32       42    183       45.75


## Combining Files

Of course sometimes our data is split between multiple sources and we need to combine them. In this next section we are goingto look at the different forms of combination we can do in Pandas.

In [ ]:
# Let's start by loading in a second data file
# and having a look at it.

df_city = pd.read_csv('ScoreBook2.csv', dtype={'participant' : 'string'})
df_city = df_city.rename(columns={"participant":"id"})
df_city

# You can see that this is the city assocaited with each participant
# Notice that I renamed the id column that we are going to match to the
# first data set.

id    city
0  01234  London
1  56782    York
2  36789    York
3  46923   Leeds
4  56723   Leeds
5  61378    York
6  74892  London
7  85243  London
8  97823   Leeds
9  10674    York

In [ ]:
# Join Data Sets, Commonly we will have two files we need to join them
# using the 'merge' function.

result = pd.merge(df, df_city, on='id')
print(result)

      id  age   pref  score_1  score_2  score_3  total  percentage    city
0  01234   25   True       45       18       89    241       60.25  London
1  56782   18   True       67       32       42    183       45.75    York
2  36789   19  False       32       76       54    216       54.00    York
3  46923   32  False       78       46       67    258       64.50   Leeds
4  56723   47  False       78       48       32    190       47.50   Leeds
5  61378   65   True       82       87       67    303       75.75    York
6  74892   22   True       45       46       89    269       67.25  London
7  85243   29  False       56       75       82    295       73.75  London
8  97823   36  False       52       24       63    202       50.50   Leeds
9  10674   44   True       12       56       67    202       50.50    York


In [ ]:
# Well that was nice because the data was well behaved.
# what about this?

df_missingone = drop_row(df, '61378', col_name='id')
df_missingone

result = pd.merge(df_missingone, df_city, on='id')
result

# Notice that we lose a row from the data set.
# not only that but the resulting data set has had a new set
# of row numbers generated.

id  age   pref  score_1  score_2  score_3  total  percentage    city
0  01234   25   True       45       18       89    241       60.25  London
1  56782   18   True       67       32       42    183       45.75    York
2  36789   19  False       32       76       54    216       54.00    York
3  46923   32  False       78       46       67    258       64.50   Leeds
4  56723   47  False       78       48       32    190       47.50   Leeds
5  74892   22   True       45       46       89    269       67.25  London
6  85243   29  False       56       75       82    295       73.75  London
7  97823   36  False       52       24       63    202       50.50   Leeds
8  10674   44   True       12       56       67    202       50.50    York

In [ ]:
# if we want to keep all the rows then we can use the 'how'
# parameter, obviously there is no data for the extra participants apart from
# the city and therefore the data is replaced with NaN (not a number) which
# we can interpret as missing.

result = pd.merge(df_missingone, df_city, on='id', how='outer')
print(result)

      id   age   pref  score_1  score_2  score_3  total  percentage    city
0  01234  25.0   True     45.0     18.0     89.0  241.0       60.25  London
1  56782  18.0   True     67.0     32.0     42.0  183.0       45.75    York
2  36789  19.0  False     32.0     76.0     54.0  216.0       54.00    York
3  46923  32.0  False     78.0     46.0     67.0  258.0       64.50   Leeds
4  56723  47.0  False     78.0     48.0     32.0  190.0       47.50   Leeds
5  74892  22.0   True     45.0     46.0     89.0  269.0       67.25  London
6  85243  29.0  False     56.0     75.0     82.0  295.0       73.75  London
7  97823  36.0  False     52.0     24.0     63.0  202.0       50.50   Leeds
8  10674  44.0   True     12.0     56.0     67.0  202.0       50.50    York
9  61378   NaN    NaN      NaN      NaN      NaN    NaN         NaN    York


In [ ]:
# Let's try that again but this time drop a row from the city data set

missing_city = drop_row(df_city, '61378', col_name='id')
result = pd.merge(df, missing_city, on='id', how='outer')
result

id  age   pref  score_1  score_2  score_3  total  percentage    city
0  01234   25   True       45       18       89    241       60.25  London
1  56782   18   True       67       32       42    183       45.75    York
2  36789   19  False       32       76       54    216       54.00    York
3  46923   32  False       78       46       67    258       64.50   Leeds
4  56723   47  False       78       48       32    190       47.50   Leeds
5  61378   65   True       82       87       67    303       75.75     NaN
6  74892   22   True       45       46       89    269       67.25  London
7  85243   29  False       56       75       82    295       73.75  London
8  97823   36  False       52       24       63    202       50.50   Leeds
9  10674   44   True       12       56       67    202       50.50    York

## Adding new rows.

Sometimes we simply want to add more rows to an existing set. Maybe the data collection was undertaken over multiple days, or by multiple people.


In [ ]:
# Let's start by reading in the two csv files we are interested in.

df_first = pd.read_csv('ScoreBook.csv', dtype={'participant' : 'string'})
df_first = df_first.rename(columns={"participant":"id"})
df_first

df_second = pd.read_csv('ScoreBook3.csv', dtype={'participant' : 'string'})
df_second = df_second.rename(columns={"participant":"id"})
df_second

# Next check that they have the same number of columns?

print(f"shape 1 {df_first.shape}")
print(f"shape 2 {df_second.shape}")
print()

print(df_second)

shape 1 (10, 6)
shape 2 (3, 6)

      id  age  pref  score_1  score_2  score_3
0  91546   32     1       48       22       56
1  87534   19     2       56       28       87
2  56341   56     2       35       56       54


In [ ]:
# Now we can do the work we need to and join the two files together using the concat function
df_full = pd.concat([df_first,df_second])
print(df_full.shape)
print()

# Now let's that a look at the dataframe
print(df_full)

(13, 6)

      id  age  pref  score_1  score_2  score_3
0  01234   25     1       45       18       89
1  56782   18     1       67       32       42
2  36789   19     0       32       76       54
3  46923   32     0       78       46       67
4  56723   47     0       78       48       32
5  61378   65     1       82       87       67
6  74892   22     1       45       46       89
7  85243   29     0       56       75       82
8  97823   36     0       52       24       63
9  10674   44     1       12       56       67
0  91546   32     1       48       22       56
1  87534   19     2       56       28       87
2  56341   56     2       35       56       54


In [ ]:
# oops, it looks like the row numbers are being reused.
# well we can fix that.

df_full = pd.concat([df_first,df_second], ignore_index=True)
print(df_full)

       id  age  pref  score_1  score_2  score_3
0   01234   25     1       45       18       89
1   56782   18     1       67       32       42
2   36789   19     0       32       76       54
3   46923   32     0       78       46       67
4   56723   47     0       78       48       32
5   61378   65     1       82       87       67
6   74892   22     1       45       46       89
7   85243   29     0       56       75       82
8   97823   36     0       52       24       63
9   10674   44     1       12       56       67
10  91546   32     1       48       22       56
11  87534   19     2       56       28       87
12  56341   56     2       35       56       54


In [ ]:
# Now Pandas can undertake a massive amount of manipulation and I'll leave that
# for another day (or you own investigation) but let me show you something
# useful

# Data Aggregation and grouping
#
# we might well want to group our data and get information.
# here we want to know how many preople live in each city (for our earlier tables.).
# so we will group the participants by city and then count how many in each group

print(result)


s = result.groupby('city').count()
print(s)

      id  age   pref  score_1  score_2  score_3  total  percentage    city
0  01234   25   True       45       18       89    241       60.25  London
1  56782   18   True       67       32       42    183       45.75    York
2  36789   19  False       32       76       54    216       54.00    York
3  46923   32  False       78       46       67    258       64.50   Leeds
4  56723   47  False       78       48       32    190       47.50   Leeds
5  61378   65   True       82       87       67    303       75.75     NaN
6  74892   22   True       45       46       89    269       67.25  London
7  85243   29  False       56       75       82    295       73.75  London
8  97823   36  False       52       24       63    202       50.50   Leeds
9  10674   44   True       12       56       67    202       50.50    York
        id  age  pref  score_1  score_2  score_3  total  percentage
city                                                               
Leeds    3    3     3        3        3

In [ ]:
# As well as count we can add things up for each group using the sum function

s = result.groupby('city').agg('sum')
print(s)

                     id  age  pref  score_1  score_2  score_3  total  \
city                                                                   
Leeds   469235672397823  115     0      208      118      162    650   
London  012347489285243   76     2      146      139      260    805   
York    567823678910674   81     2      111      164      163    601   

        percentage  
city                
Leeds       162.50  
London      201.25  
York        150.25  


In [ ]:
# Finally you might want to group by more than one column.
# let's try that

s = result.groupby(['city', 'pref']).agg('sum')
print(s)


# and of course we could just look at a single column of the result
print("------ age column only ------")
print(s['age'])



                           id  age  score_1  score_2  score_3  total  \
city   pref                                                            
Leeds  False  469235672397823  115      208      118      162    650   
London False            85243   29       56       75       82    295   
       True        0123474892   47       90       64      178    510   
York   False            36789   19       32       76       54    216   
       True        5678210674   62       79       88      109    385   

              percentage  
city   pref               
Leeds  False      162.50  
London False       73.75  
       True       127.50  
York   False       54.00  
       True        96.25  
------ age column only ------
city    pref 
Leeds   False    115
London  False     29
        True      47
York    False     19
        True      62
Name: age, dtype: int64


In [ ]:
# Just before we finish this bit, let's try and get the mean of the columns when grouped

# s = result.groupby(['city', 'pref']).agg('mean')


# This throws and error telling us that we can't use mean on string data.
# Well all we wanted was the mean of age and total so un comment the next line
# and comment out the previous code

s = result.groupby(['city', 'pref'])[['age', 'total']].agg('mean')
print(s)

# if you want to see more of this kind of operation search the internet for
# Pandas grouping and aggregation.


                    age       total
city   pref                        
Leeds  False  38.333333  216.666667
London False  29.000000  295.000000
       True   23.500000  255.000000
York   False  19.000000  216.000000
       True   31.000000  192.500000


# NHS Data

In this section I'm going to make use of some data taken from the internet.
You can find the compelte dataset at the nhs website, but I've created a smaller
set from this data and put it on my university website for convenience.

https://data.england.nhs.uk/dataset/a-e-synthetic-data

https://www-users.york.ac.uk/~cap508/resources/NHS_Sample.csv



In [ ]:
# Because this data has been put onto a website Pandas gives us the opportunity
# to load it directly from the url

url = 'https://www-users.york.ac.uk/~cap508/resources/NHS_Sample.csv'

df = pd.read_csv(url)

In [ ]:
# What is in this data set? The columns command will give you the name of each column

print(df.columns)

Index(['Unnamed: 0', 'IMD_Decile_From_LSOA', 'Age_Band', 'Sex',
       'AE_Arrive_Date', 'AE_Arrive_HourOfDay', 'AE_Time_Mins', 'AE_HRG',
       'AE_Num_Diagnoses', 'AE_Num_Investigations', 'AE_Num_Treatments',
       'AE_Arrival_Mode', 'Provider_Patient_Distance_Miles', 'ProvID',
       'Admitted_Flag', 'Admission_Method', 'ICD10_Chapter_Code',
       'Treatment_Function_Code', 'Length_Of_Stay_Days'],
      dtype='object')


In [ ]:
# The head command will show is the top of the data frame, can you guess how you might see the bottom?

df.head(10)



Unnamed: 0  IMD_Decile_From_LSOA Age_Band  Sex       AE_Arrive_Date  \
0           0                     2    65-84    1  2015-07-02 00:00:00   
1           1                     6    18-24    1  2017-05-31 00:00:00   
2           2                     2    65-84    2  2015-10-25 00:00:00   
3           3                     4    25-44    1  2014-06-16 00:00:00   
4           4                     7    18-24    2  2017-11-18 00:00:00   
5           5                     4      85+    2  2015-09-30 00:00:00   
6           6                     8    65-84    2  2015-02-04 00:00:00   
7           7                     2    45-64    2  2015-01-11 00:00:00   
8           8                     7     1-17    2  2016-11-17 00:00:00   
9           9                     3    65-84    2  2018-01-12 00:00:00   

  AE_Arrive_HourOfDay  AE_Time_Mins   AE_HRG  AE_Num_Diagnoses  \
0               17-20           210     High                 1   
1               17-20            20      Low                 0   
2               13-16           280  Nothing                 1   
3               21-24           150      Low                 1   
4               13-16           180      Low                 1   
5               13-16           240      Low                 1   
6               09-12           160  Nothing                 0   
7               09-12           210      Low                 2   
8               09-12            30  Nothing                 1   
9               17-20           100      Low                 1   

   AE_Num_Investigations  AE_Num_Treatments  AE_Arrival_Mode  \
0                      5                  3                2   
1                      1                  1                2   
2                      0                  1                1   
3                      2                  2                2   
4                      1                  2                2   
5                     10                 10                1   
6                      1                  1                1   
7                      2                  1                2   
8                      1                  1                2   
9                      1                  1                2   

   Provider_Patient_Distance_Miles  ProvID  Admitted_Flag  Admission_Method  \
0                                1   15207              1              21.0   
1                                5   15321              0               NaN   
2                                2   15269              0               NaN   
3                                1   15239              0               NaN   
4                                1   15286              0               NaN   
5                                2   15310              1              21.0   
6                                2   15260              1              21.0   
7                               13   15312              0               NaN   
8                                9   15396              0               NaN   
9                                0   15383              0               NaN   

  ICD10_Chapter_Code Treatment_Function_Code  Length_Of_Stay_Days  
0              XVIII                     180                  1.0  
1                NaN                     NaN                  NaN  
2                NaN                     NaN                  NaN  
3                NaN                     NaN                  NaN  
4                NaN                     NaN                  NaN  
5                 IX                   OTHER                 16.0  
6              XVIII                     300                  1.0  
7                NaN                     NaN                  NaN  
8                NaN                     NaN                  NaN  
9                NaN                     NaN                  NaN

In [ ]:
# If we only want to see part of the data we can use range command

df[3:5] # How only rows 3 to 5, notice that the upper bound is non-inclusive

Unnamed: 0  IMD_Decile_From_LSOA Age_Band  Sex       AE_Arrive_Date  \
3           3                     4    25-44    1  2014-06-16 00:00:00   
4           4                     7    18-24    2  2017-11-18 00:00:00   

  AE_Arrive_HourOfDay  AE_Time_Mins AE_HRG  AE_Num_Diagnoses  \
3               21-24           150    Low                 1   
4               13-16           180    Low                 1   

   AE_Num_Investigations  AE_Num_Treatments  AE_Arrival_Mode  \
3                      2                  2                2   
4                      1                  2                2   

   Provider_Patient_Distance_Miles  ProvID  Admitted_Flag  Admission_Method  \
3                                1   15239              0               NaN   
4                                1   15286              0               NaN   

  ICD10_Chapter_Code Treatment_Function_Code  Length_Of_Stay_Days  
3                NaN                     NaN                  NaN  
4                NaN                     NaN                  NaN

In [ ]:
df.loc[0:5,["AE_Arrive_Date", "AE_HRG"]]

AE_Arrive_Date   AE_HRG
0  2015-07-02 00:00:00     High
1  2017-05-31 00:00:00      Low
2  2015-10-25 00:00:00  Nothing
3  2014-06-16 00:00:00      Low
4  2017-11-18 00:00:00      Low
5  2015-09-30 00:00:00      Low

In [ ]:
# Of course we can also use the filtering commands we saw earlier

df[df.AE_HRG == "Nothing"]

Unnamed: 0  IMD_Decile_From_LSOA Age_Band  Sex       AE_Arrive_Date  \
2             2                     2    65-84    2  2015-10-25 00:00:00   
6             6                     8    65-84    2  2015-02-04 00:00:00   
8             8                     7     1-17    2  2016-11-17 00:00:00   
11           11                     7     1-17    1  2015-03-01 00:00:00   
30           30                     5    25-44    2  2016-12-30 00:00:00   
..          ...                   ...      ...  ...                  ...   
985         985                     2     1-17    1  2016-07-14 00:00:00   
986         986                     5    25-44    2  2015-07-21 00:00:00   
991         991                     6      85+    2  2015-02-14 00:00:00   
992         992                     4    25-44    1  2016-11-27 00:00:00   
997         997                     4    45-64    1  2016-02-23 00:00:00   

    AE_Arrive_HourOfDay  AE_Time_Mins   AE_HRG  AE_Num_Diagnoses  \
2                 13-16           280  Nothing                 1   
6                 09-12           160  Nothing                 0   
8                 09-12            30  Nothing                 1   
11                09-12           130  Nothing                 1   
30                09-12            60  Nothing                 0   
..                  ...           ...      ...               ...   
985               17-20           240  Nothing                 0   
986               17-20            90  Nothing                 1   
991               09-12           220  Nothing                 0   
992               13-16           120  Nothing                 1   
997               09-12           170  Nothing                 0   

     AE_Num_Investigations  AE_Num_Treatments  AE_Arrival_Mode  \
2                        0                  1                1   
6                        1                  1                1   
8                        1                  1                2   
11                       1                  2                2   
30                       1                  0                2   
..                     ...                ...              ...   
985                      2                  2                2   
986                      1                  1                2   
991                      1                  0                2   
992                      1                  1                2   
997                      2                  2                2   

     Provider_Patient_Distance_Miles  ProvID  Admitted_Flag  Admission_Method  \
2                                  2   15269              0               NaN   
6                                  2   15260              1              21.0   
8                                  9   15396              0               NaN   
11                                 1   32338              0               NaN   
30                                 1   25911              0               NaN   
..                               ...     ...            ...               ...   
985                                3   15199              0               NaN   
986                                1   15323              0               NaN   
991                                1   15214              0               NaN   
992                                0   15144              0               NaN   
997                                3   15199              0               NaN   

    ICD10_Chapter_Code Treatment_Function_Code  Length_Of_Stay_Days  
2                  NaN                     NaN                  NaN  
6                XVIII                     300                  1.0  
8                  NaN                     NaN                  NaN  
11                 NaN                     NaN                  NaN  
30                 NaN                     NaN                  NaN  
..                 ...                     ...                  ...  
985                

In [ ]:
# We can then use this to select information. So the qustion might be
# what is the hour of the day for people haveing an AE_Time of > 200

subset = df[df.AE_Time_Mins > 200]
print(f"{subset.shape[0]} patients had a wait of over 200 minutes")
print("Here are their arival times")
print(subset.loc[:,['AE_Arrive_HourOfDay', 'AE_Time_Mins']])



288 patients had a wait of over 200 minutes
Here are their arival times
    AE_Arrive_HourOfDay  AE_Time_Mins
0                 17-20           210
2                 13-16           280
5                 13-16           240
7                 09-12           210
13                01-04           210
..                  ...           ...
989               17-20           230
990               09-12           220
991               09-12           220
994               13-16           340
999               17-20           240

[288 rows x 2 columns]


In [ ]:
# There is also a very useful command called query
# to cover it in detail is a bi much but you should know it exists.

df.query('AE_Time_Mins > 200 and AE_Num_Diagnoses == 2 and AE_Num_Investigations > 3')


Unnamed: 0  IMD_Decile_From_LSOA Age_Band  Sex       AE_Arrive_Date  \
332         332                     5    25-44    1  2016-11-10 00:00:00   
336         336                     3    45-64    1  2015-02-25 00:00:00   
477         477                    10    25-44    1  2014-04-02 00:00:00   
559         559                     7     1-17    1  2017-05-05 00:00:00   
633         633                     2     1-17    2  2014-04-25 00:00:00   
759         759                     5    45-64    1  2017-10-04 00:00:00   
972         972                     2    18-24    2  2016-07-20 00:00:00   
987         987                     3    45-64    1  2016-08-03 00:00:00   

    AE_Arrive_HourOfDay  AE_Time_Mins  AE_HRG  AE_Num_Diagnoses  \
332               17-20           350     Low                 2   
336               21-24           380  Medium                 2   
477               13-16           420    High                 2   
559               17-20           270     Low                 2   
633               21-24           610     Low                 2   
759               09-12           420    High                 2   
972               17-20           470  Medium                 2   
987               13-16           230     Low                 2   

     AE_Num_Investigations  AE_Num_Treatments  AE_Arrival_Mode  \
332                     10                 10                2   
336                     10                 10                1   
477                      4                 10                2   
559                     10                 10                2   
633                      6                  2                2   
759                      7                  5                2   
972                      6                  3                1   
987                      4                  1                0   

     Provider_Patient_Distance_Miles  ProvID  Admitted_Flag  Admission_Method  \
332                               11   15147              0               NaN   
336                                1   15147              0               NaN   
477                                3   15297              1              21.0   
559                                7   15234              0               NaN   
633                                1   15319              1              21.0   
759                               12   15143              1              21.0   
972                                2   15361              1              21.0   
987                                3   15217              0               NaN   

    ICD10_Chapter_Code Treatment_Function_Code  Length_Of_Stay_Days  
332                NaN                     NaN                  NaN  
336                NaN                     NaN                  NaN  
477                 IX                   OTHER                  2.0  
559                NaN                     NaN                  NaN  
633              Other                     420                  0.0  
759              Other                   OTHER                  4.0  
972              Other                     300                  4.0  
987                NaN                     NaN                  NaN

In [ ]:
# We can then just look at the columns we are interested in
df.query('AE_Time_Mins > 200 and AE_Num_Diagnoses == 2 and AE_Num_Investigations > 3')[["Age_Band", "AE_Num_Treatments"]]


# So the first bit returns the subset of data then the next bit says these are the columns we want to see.

Age_Band  AE_Num_Treatments
332    25-44                 10
336    45-64                 10
477    25-44                 10
559     1-17                 10
633     1-17                  2
759    45-64                  5
972    18-24                  3
987    45-64                  1

That's it for this work sheet. Next we're going to move onto visualising data which is great for creating graphs for use in your presentaions, reports and papers.